name: Release binaries

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        go: ["1.22"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          go build -o artifacts/keda-celery-scaler-linux-x64 main.go
      - name: Build MacOS
        if: matrix.os == 'macos-latest'
        run: |
          go build -o artifacts/keda-celery-scaler-mac-x64 main.go
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          go build -o artifacts/keda-celery-scaler-windows-x64 main.go
      - uses: actions/upload-artifact@v4
        with:
          name: builds
          path: artifacts
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "artifacts/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
